logging:
  level:
    org:
      springframework: INFO
    com:
      sap:
        olingo:
          jpa: TRACE      
odata:
  jpa:
    punit_name: _s_t_s_-_b_u_s_-_v_1_4_
    root_packages: com
server:
  port: 8080
spring:
  liquibase:
    change-log: classpath:db/liquibase_changelog.xml
    enabled: true
  servlet:
    multipart:
      enabled: false